### ISSUE TITLE
Requesting Help for input tree file creating by sequence variant file such as vcf file

### ISSUE THREAD

**Issue by Yung-Chien** [michaelmiyagi/QuIBL#12]
Hi @miriammiyagi ,
I'm curious about if QuiBL could be used in the tree file created by sequence variant file such as vcf(include SNPs and|or INDELs) format file. And if so, how could I prepare the input file and what kind of threshold for filtration should I select? Thanks in advances.
Best Regards,
Yung-Chien

**Comment by miriammiyagi** [comment]
Hi Yung-Chien,

Sorry, I'm not totally clear on what you mean- what QuIBL needs is a list of gene trees with branch lengths. You could certainly generate them using your data from a VCF file, combined with a reference sequence and a likelihood-based tree estimation program of your choosing. I believe you could also use RAxML with an ascertainment bias correction for only having SNPs to infer the trees, but I have not personally used that pipeline. The important thing is that you need to have estimates for the branch lengths, as otherwise QuIBL won't have anything to go off of!

Hopefully this helps a bit, let me know if you have further questions!
Mia
