### ISSUE TITLE
Introgression direction

### ISSUE THREAD

**Issue by tangerzhang** [michaelmiyagi/QuIBL#6]
Thanks for providing such a wonder tool to detect non-ILS introgression. I have one question regarding the usage of this program.
The example you provided in github (https://github.com/michaelmiyagi/QuIBL/) shows loci with |A_B_C|A| topology is likely an introgression event. Since A is an outgroup, I assume that the introgression occurred between B and C. However, is it possible to determine the direction of this introgression event, from B to C or from C to B?

**Comment by michaelmiyagi** [comment]
Thanks for the question- at the moment, there is not an automated way to get the direction of introgression. However, using the output from QuIBL, you may be able to tell manually: if the inferred "C2" value for the introgression topology is longer than the species tree topology "C2" value, that suggests that the direction of gene flow is from B->C backwards in time, since that introgression direction results in a longer internal branch. If it's shorter, then it hints towards the opposite. However, we don't have a measure of significance for the difference in these values, so if they're relatively close it's not strong evidence one way or the other.

**Comment by tangerzhang** [comment]
Got it. Thanks!
